#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp14
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PROJEKAT2")]
	public partial class zaposleniDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertzaposleni(zaposleni instance);
    partial void Updatezaposleni(zaposleni instance);
    partial void Deletezaposleni(zaposleni instance);
    #endregion
		
		public zaposleniDataContext() : 
				base(global::WindowsFormsApp14.Properties.Settings.Default.PROJEKAT2ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public zaposleniDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public zaposleniDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public zaposleniDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public zaposleniDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<zaposleni> zaposlenis
		{
			get
			{
				return this.GetTable<zaposleni>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zaposleni")]
	public partial class zaposleni : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ime;
		
		private string _Prezime;
		
		private System.Nullable<System.DateTime> _DatumRodjenja;
		
		private string _MjestoRodjenja;
		
		private string _JMBG;
		
		private string _Pol;
		
		private string _Drzavljanstvo;
		
		private string _RadnoMjesto;
		
		private System.Nullable<System.DateTime> _DatumZaposlenja;
		
		private System.Nullable<int> _Staz;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnImeChanging(string value);
    partial void OnImeChanged();
    partial void OnPrezimeChanging(string value);
    partial void OnPrezimeChanged();
    partial void OnDatumRodjenjaChanging(System.Nullable<System.DateTime> value);
    partial void OnDatumRodjenjaChanged();
    partial void OnMjestoRodjenjaChanging(string value);
    partial void OnMjestoRodjenjaChanged();
    partial void OnJMBGChanging(string value);
    partial void OnJMBGChanged();
    partial void OnPolChanging(string value);
    partial void OnPolChanged();
    partial void OnDrzavljanstvoChanging(string value);
    partial void OnDrzavljanstvoChanged();
    partial void OnRadnoMjestoChanging(string value);
    partial void OnRadnoMjestoChanged();
    partial void OnDatumZaposlenjaChanging(System.Nullable<System.DateTime> value);
    partial void OnDatumZaposlenjaChanged();
    partial void OnStazChanging(System.Nullable<int> value);
    partial void OnStazChanged();
    #endregion
		
		public zaposleni()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ime", DbType="NChar(100)")]
		public string Ime
		{
			get
			{
				return this._Ime;
			}
			set
			{
				if ((this._Ime != value))
				{
					this.OnImeChanging(value);
					this.SendPropertyChanging();
					this._Ime = value;
					this.SendPropertyChanged("Ime");
					this.OnImeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prezime", DbType="NChar(100)")]
		public string Prezime
		{
			get
			{
				return this._Prezime;
			}
			set
			{
				if ((this._Prezime != value))
				{
					this.OnPrezimeChanging(value);
					this.SendPropertyChanging();
					this._Prezime = value;
					this.SendPropertyChanged("Prezime");
					this.OnPrezimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumRodjenja", DbType="Date")]
		public System.Nullable<System.DateTime> DatumRodjenja
		{
			get
			{
				return this._DatumRodjenja;
			}
			set
			{
				if ((this._DatumRodjenja != value))
				{
					this.OnDatumRodjenjaChanging(value);
					this.SendPropertyChanging();
					this._DatumRodjenja = value;
					this.SendPropertyChanged("DatumRodjenja");
					this.OnDatumRodjenjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MjestoRodjenja", DbType="NChar(100)")]
		public string MjestoRodjenja
		{
			get
			{
				return this._MjestoRodjenja;
			}
			set
			{
				if ((this._MjestoRodjenja != value))
				{
					this.OnMjestoRodjenjaChanging(value);
					this.SendPropertyChanging();
					this._MjestoRodjenja = value;
					this.SendPropertyChanged("MjestoRodjenja");
					this.OnMjestoRodjenjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JMBG", DbType="NChar(13)")]
		public string JMBG
		{
			get
			{
				return this._JMBG;
			}
			set
			{
				if ((this._JMBG != value))
				{
					this.OnJMBGChanging(value);
					this.SendPropertyChanging();
					this._JMBG = value;
					this.SendPropertyChanged("JMBG");
					this.OnJMBGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pol", DbType="NChar(2)")]
		public string Pol
		{
			get
			{
				return this._Pol;
			}
			set
			{
				if ((this._Pol != value))
				{
					this.OnPolChanging(value);
					this.SendPropertyChanging();
					this._Pol = value;
					this.SendPropertyChanged("Pol");
					this.OnPolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Drzavljanstvo", DbType="NChar(10)")]
		public string Drzavljanstvo
		{
			get
			{
				return this._Drzavljanstvo;
			}
			set
			{
				if ((this._Drzavljanstvo != value))
				{
					this.OnDrzavljanstvoChanging(value);
					this.SendPropertyChanging();
					this._Drzavljanstvo = value;
					this.SendPropertyChanged("Drzavljanstvo");
					this.OnDrzavljanstvoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RadnoMjesto", DbType="NChar(100)")]
		public string RadnoMjesto
		{
			get
			{
				return this._RadnoMjesto;
			}
			set
			{
				if ((this._RadnoMjesto != value))
				{
					this.OnRadnoMjestoChanging(value);
					this.SendPropertyChanging();
					this._RadnoMjesto = value;
					this.SendPropertyChanged("RadnoMjesto");
					this.OnRadnoMjestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumZaposlenja", DbType="Date")]
		public System.Nullable<System.DateTime> DatumZaposlenja
		{
			get
			{
				return this._DatumZaposlenja;
			}
			set
			{
				if ((this._DatumZaposlenja != value))
				{
					this.OnDatumZaposlenjaChanging(value);
					this.SendPropertyChanging();
					this._DatumZaposlenja = value;
					this.SendPropertyChanged("DatumZaposlenja");
					this.OnDatumZaposlenjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staz", DbType="Int")]
		public System.Nullable<int> Staz
		{
			get
			{
				return this._Staz;
			}
			set
			{
				if ((this._Staz != value))
				{
					this.OnStazChanging(value);
					this.SendPropertyChanging();
					this._Staz = value;
					this.SendPropertyChanged("Staz");
					this.OnStazChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
